### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by alexeyschepin**
Bump rubocop version

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by palin** [comment]
Please make the version 2.4.0 and LGTM

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Review by palin — APPROVED** [review]
LGTM

**Pull request merged**
