### PR TITLE
Disable max method length

### PR DESCRIPTION
**Pull request by davidsevcik**

### CODE REVIEW

**Comment by errm** [comment]
I think that this is too long.

Methods start to get complex around 5 lines, 10 lines are often horrid, and 15 without fail are in need of refactoring.

I think it is much better to be forced to explicitly disable this cop on a case by case basis if there is no other option.

**Comment by errm** [comment]
Sandi says 5 lines https://robots.thoughtbot.com/sandi-metz-rules-for-developers I think 10 is a good compromise while we have so much ancient code . . .

**Comment by lpil** [comment]
I think that the number of lines is an attempt to measure complexity in a way that is simple enough for a person to do easily. Rubocop isn't a person, and has other (better?) ways of measuring complexity.

As there's these other checks, I'd be happy with disabling the method length cop.

Additionally this cop discourages you from formatting your code nicely, instead it trains you to put everything on one long line. Clarity > low number of lines.

**Comment by mikekr1** [comment]
One long line up to 80 chars ;)

**Comment by lpil** [comment]
120 atm. I would like it to be 80.

**Comment by jonnyarnold** [comment]
I'm with @lpil on this one; the ABC complexity metric is more than enough discouragement for long methods.

**Comment by davidsevcik** [comment]
:+1: for disabling method length. we are grown up :)

**Comment by jonnyarnold** [comment]
I've updated this to disable the max method length. Please review :lollipop:

**Pull request merged**
